call plug#begin('/home/probe/.config/nvim/plugged')
	Plug 'michaelb/vim-tips'
	Plug 'kyazdani42/nvim-web-devicons'
	Plug 'ryanoasis/vim-devicons'
	Plug 'tpope/vim-fugitive'
	Plug 'ap/vim-css-color'
	Plug 'dart-lang/dart-vim-plugin'
	Plug 'tpope/vim-markdown'
	Plug 'preservim/nerdtree'
call plug#end()
