#!/bin/sh

picom &
xsetroot -cursor_name left_ptr &
xrandr --output eDP-1 --set CTM '1431655765,1,715827882,-2147483648,715827882,-2147483648,715827882,-2147483648,1431655765,1,715827882,-2147483648,715827882,-2147483648,715827882,-2147483648,1431655765,1' --gamma 0.9 &
xset -b &
feh --bg-fill --no-fehbg /home/probe/.config/bspwm/wal.jpg &
/home/probe/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 零

bspc config border_width        2
bspc config focused_border_color "#444b6a"
#bspc config normal_border_color  "#32344a"
#bspc config active_border_color  "#444b6a"
bspc config window_gap          20
bspc config top_padding         30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
