#!/bin/sh

picom &
xrandr --output eDP1 --gamma 0.8:0.8:0.8 &
xsetroot -cursor_name left_ptr &
xset -b &
feh --bg-fill /home/probe/.config/bspwm/wal.jpg &
/home/probe/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
#bspc config focused_border_color "#7bc5e4"
#bspc config normal_border_color  "#32344a"
#bspc config active_border_color  "#444b6a"
bspc config window_gap          20
bspc config top_padding         29

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
